from __future__ import annotations

from pathlib import Path
import os
import subprocess
import sys

from ..artifact_store import ArtifactStore
from ..models import ToolResult, new_id
from ..tool_registry import ToolRegistry


class CodeExecutionTools:
    def __init__(self, data_dir: Path, artifacts: ArtifactStore, max_preview_bytes: int):
        self.execution_root = data_dir / "executions"
        self.execution_root.mkdir(parents=True, exist_ok=True)
        self.artifacts = artifacts
        self.max_preview_bytes = max_preview_bytes

    def execute_python(self, code: str, timeout_seconds: int = 10, *, call_id: str) -> ToolResult:
        execution_dir = self.execution_root / new_id("execution")
        execution_dir.mkdir()
        program = execution_dir / "program.py"
        program.write_text(code, encoding="utf-8")
        environment = {"PATH": os.environ.get("PATH", "/usr/bin:/bin"), "PYTHONIOENCODING": "utf-8"}
        try:
            completed = subprocess.run(
                [sys.executable, "-I", program.name],
                cwd=execution_dir,
                env=environment,
                capture_output=True,
                timeout=timeout_seconds,
                check=False,
            )
        except subprocess.TimeoutExpired as exc:
            output = (exc.stdout or b"") + (exc.stderr or b"")
            artifacts = []
            if output:
                artifacts.append(self.artifacts.save_bytes(output, suffix=".log", description="Timed-out Python output", call_id=call_id)["id"])
            return ToolResult(call_id, "code_execute_python", "error", f"Python timed out after {timeout_seconds}s", artifact_ids=artifacts, error="timeout")
        output = completed.stdout + (b"\n[stderr]\n" + completed.stderr if completed.stderr else b"")
        artifact_ids = []
        for generated in execution_dir.iterdir():
            if generated == program or not generated.is_file():
                continue
            artifact_ids.append(
                self.artifacts.save_bytes(
                    generated.read_bytes(),
                    suffix=generated.suffix or ".bin",
                    description=f"Generated by Python execution: {generated.name}",
                    call_id=call_id,
                )["id"]
            )
        truncated = len(output) > self.max_preview_bytes
        if truncated:
            artifact_ids.insert(0, self.artifacts.save_bytes(output, suffix=".log", description="Complete Python output", call_id=call_id)["id"])
        status = "success" if completed.returncode == 0 else "error"
        return ToolResult(
            call_id,
            "code_execute_python",
            status,
            f"Python exited with code {completed.returncode}",
            output[: self.max_preview_bytes].decode("utf-8", errors="replace"),
            artifact_ids,
            truncated,
            error=None if completed.returncode == 0 else "non-zero exit code",
            metadata={"exit_code": completed.returncode, "execution_dir": str(execution_dir)},
        )


def register_code_tools(registry: ToolRegistry, data_dir: Path, artifacts: ArtifactStore, max_preview_bytes: int) -> None:
    tools = CodeExecutionTools(data_dir, artifacts, max_preview_bytes)
    registry.register(
        "code_execute_python",
        "Execute Python in an isolated child process and return bounded output plus generated artifacts.",
        {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "code": {"type": "string"},
                "timeout_seconds": {"type": "integer", "minimum": 1, "maximum": 60},
            },
            "required": ["code"],
        },
        tools.execute_python,
    )
